name: backend CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend

    strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tempo-test
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Configure environment variables
        run: echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_DATABASE: myapp_test
        run: node ace migration:run --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
          DB_DATABASE: tempo-test
          NODE_ENV: test
        run: pnpm run test
